import type { Metadata } from "next";
import { Sansita } from "next/font/google";
import "./globals.css";

const sansita = Sansita({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sansita.className}>{children}</body>
    </html>
  );
}
