import { BundleDuration, BundleModel } from "@/helpers/models/bundle.model";
import { z } from "zod";
import { createServerAction } from "zsa";

export const getBundlesAction = createServerAction()
  .input(z.object({ limit: z.optional(z.number()) }))
  .handler<Promise<BundleModel[]>>(async ({ input }) => {

    await new Promise((resolve) => setTimeout(resolve, 5000));
    return [
          {
            id: "1",
            name: "Surf week",
            operator: "tigo",
            description: "1 GO valable pour une semain.",
            price: "1250 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "30",
            name: "Airtel Month",
            operator: "airtel",
            description: "3 GB à 3000 frs pour un mois avec Airtel Money",
            price: "3000 frs",
            duration: BundleDuration.MONTH,
          }, 
          {
            id: "4",
            name: "Surf week",
            operator: "tigo",
            description: "6 GO valable pour une semain avec Moove Money.",
            price: "2500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "39",
            name: "Salam Month",
            operator: "salam",
            description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In fugiat ratione soluta!",
            price: "1300f",
            duration: BundleDuration.MONTH,
          },
          {
            id: "5",
            name: "Surf week",
            operator: "tigo",
            description: "8 GO valable pour une semain.",
            price: "3500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "6",
            name: "Surf week",
            operator: "tigo",
            description: "12 GO valable pour une semain avec Moove money.",
            price: "3500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "7",
            name: "Surf week",
            operator: "airtel",
            description: "1 GO valable pour une semain.",
            price: "1250 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "8",
            name: "Surf week",
            operator: "airtel",
            description: "1,5 GO valable pour une semain.",
            price: "1500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "9",
            name: "Surf week",
            operator: "airtel",
            description: "4 GO valable pour une semain.",
            price: "2500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "2",
            name: "Surf week",
            operator: "tigo",
            description: "1,5 GO valable pour une semain.",
            price: "1500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "3",
            name: "Surf week",
            operator: "tigo",
            description: "4 GO valable pour une semain.",
            price: "2500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "10",
            name: "Surf week",
            operator: "airtel",
            description: "6 GO valable pour une semain avec Airtel Money.",
            price: "2500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "13",
            name: "Surf Night",
            operator: "airtel",
            description: "100 MB à 250 frs pour une journée 24h",
            price: "250 frs",
            duration: BundleDuration.DAY,
          },
          {
            id: "14",
            name: "Surf Night",
            operator: "airtel",
            description: "300 MB à 350 frs pour une journée 24f",
            price: "350 frs",
            duration: BundleDuration.DAY,
          },
          {
            id: "15",
            name: "Surf Night",
            operator: "airtel",
            description: "1 GB à 550 frs pour une journée 24f",
            price: "550 frs",
            duration: BundleDuration.DAY,
          },
          {
            id: "16",
            name: "Surf Night",
            operator: "tigo",
            description: "100 MB à 250 frs pour une journée 24h",
            price: "250 frs",
            duration: BundleDuration.DAY,
          },
          {
            id: "17",
            name: "Surf Night",
            operator: "tigo",
            description: "300 MB à 350 frs pour une journée 24f",
            price: "350 frs",
            duration: BundleDuration.DAY,
          },
          {
            id: "18",
            name: "Surf Night",
            operator: "tigo",
            description: "1 GB à 550 frs pour une journée 24f",
            price: "550 frs",
            duration: BundleDuration.DAY,
          },
          {
            id: "11",
            name: "Surf week",
            operator: "airtel",
            description: "8 GO valable pour une semain.",
            price: "3500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "12",
            name: "Surf week",
            operator: "airtel",
            description: "12 GO valable pour une semain avec Airtel money.",
            price: "3500 frs",
            duration: BundleDuration.WEEK,
          },
          {
            id: "23",
            name: "Tigo Month",
            operator: "tigo",
            description: "6 GB à 5000 frs pour un mois avec Moov Money",
            price: "5000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "38",
            name: "GooD deal",
            operator: "salam",
            description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In fugiat ratione soluta!",
            price: "10f",
            duration: BundleDuration.WEEK,
          },
          {
            id: "24",
            name: "Tigo Month",
            operator: "tigo",
            description: "10 GB à 7000 frs pour un mois",
            price: "7000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "25",
            name: "Tigo Month",
            operator: "tigo",
            description: "15 GB à 7000 frs pour un mois avec Moov Money",
            price: "7000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "28",
            name: "Airtel Month",
            operator: "airtel",
            description: "1 GB à 2000 frs pour un mois",
            price: "2000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "26",
            name: "Tigo Month",
            operator: "tigo",
            description: "20 GB à 11500 frs pour un mois",
            price: "11500 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "27",
            name: "Tigo Month",
            operator: "tigo",
            description: "30 GB à 11500 frs pour un mois avec Moov Money",
            price: "11500 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "29",
            name: "Airtel Month",
            operator: "airtel",
            description: "2 GB à 3000 frs pour un mois",
            price: "3000 frs",
            duration: BundleDuration.MONTH,
          }, 
          {
            id: "31",
            name: "Airtel Month",
            operator: "airtel",
            description: "4 GB à 5000 frs pour un mois",
            price: "5000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "19",
            name: "Tigo Month",
            operator: "tigo",
            description: "1 GB à 2000 frs pour un mois",
            price: "2000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "20",
            name: "Tigo Month",
            operator: "tigo",
            description: "2 GB à 3000 frs pour un mois",
            price: "3000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "34",
            name: "Airtel Month",
            operator: "airtel",
            description: "15 GB à 7000 frs pour un mois avec Airtel Money",
            price: "7000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "35",
            name: "Airtel Month",
            operator: "airtel",
            description: "20 GB à 11500 frs pour un mois",
            price: "11500 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "21",
            name: "Tigo Month",
            operator: "tigo",
            description: "3 GB à 3000 frs pour un mois avec Moov Money",
            price: "3000 frs",
            duration: BundleDuration.MONTH,
          },  
          {
            id: "22",
            name: "Tigo Month",
            operator: "tigo",
            description: "4 GB à 5000 frs pour un mois",
            price: "5000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "32",
            name: "Airtel Month",
            operator: "airtel",
            description: "6 GB à 5000 frs pour un mois avec Airtel Money",
            price: "5000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "33",
            name: "Airtel Month",
            operator: "airtel",
            description: "10 GB à 7000 frs pour un mois",
            price: "7000 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "36",
            name: "Airtel Month",
            operator: "airtel",
            description: "30 GB à 11500 frs pour un mois avec Airtel Money",
            price: "11500 frs",
            duration: BundleDuration.MONTH,
          },
          {
            id: "37",
            name: "Surf Night",
            operator: "salam",
            description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. In fugiat ratione soluta!",
            price: "400f",
            duration: BundleDuration.DAY,
          },
       
        ];
  });
